### ISSUE TITLE
3.2 check latest status of room usage

### ISSUE THREAD

**Issue by vsupacha** [vsupacha/cn466-project-2024#16]
REST API
- GET request /room/status?id=???
- return JSON {"status":?, "id":?, "using":?}
- if room ID does not exist, return "status":"NOT FOUND"
- if error query room ID, return "status":"ERROR"

**Comment by 6410685041** [comment]
<img width="1005" alt="Screenshot 2567-11-25 at 16 09 42" src="https://github.com/user-attachments/assets/50591556-b020-4410-a41b-c5ce91ee9504">

- มีการสร้างเงื่อนไขเพื่อรองรับกรณีเกิด error คือกรณีที่ query ไม่ได้ และกรณีที่ไม่มีห้องตามที่กำหนด
