### ISSUE TITLE
3.3 check last event of usage condition

### ISSUE THREAD

**Issue by vsupacha** [vsupacha/cn466-project-2024#17]
REST API
- GET request /room/event?id=?&condition=?
- return JSON {"status":?, "condition":?, "timestamp":?}
- if no room ID, return "status":"NOT FOUND"
- if error query database, return "status":"ERROR"

**Comment by 6410455015** [comment]
![image](https://github.com/user-attachments/assets/f7d8f9ce-f88c-42ef-af6f-f1269fba759e)
