### ISSUE TITLE
4.1 LINE bot

### ISSUE THREAD

**Issue by vsupacha** [vsupacha/cn466-project-2024#20]
REST API with LINE messaging API
- #list to show list of all rooms
- #room_id to show latest status

**Comment by 6410615139** [comment]
![image](https://github.com/user-attachments/assets/7e8073fe-c2e1-497a-8098-9aade778e5e4)

#list success

**Comment by 6410615139** [comment]
![image](https://github.com/user-attachments/assets/f23c8d06-71ba-4a73-b79c-5f7ffbb238e7)

#room_api #list and echo success
