### ISSUE TITLE
2.1 add code to T-SIMCAM to detect brightness and report via MQTT

### ISSUE THREAD

**Issue by vsupacha** [vsupacha/cn466-project-2024#4]
Notify the following info of your .env to the team
MQTT_BROKER=
MQTT_DATA_TOPIC=
MQTT_CMD_TOPIC=

**Comment by 6410615139** [comment]
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/ae45ae92-7908-4aa4-b379-43242d3a3445">
MQTT_BROKER=mqtt.eclipseprojects.io
MQTT_DATA_TOPIC=TU/CN417/tsimcam/supakrit-cam
MQTT_CMD_TOPIC=

**Comment by vsupacha** [comment]
Merged into main branch,
