### ISSUE TITLE
2.3 room_ui = show recorded events

### ISSUE THREAD

**Issue by vsupacha** [vsupacha/cn466-project-2024#6]
Show last 5 events - timestamp, location, status

**Comment by 6410685041** [comment]
<img width="1278" alt="Screenshot 2567-11-18 at 12 09 23" src="https://github.com/user-attachments/assets/6ead6db9-dc10-43af-8aa8-48cbd99edfab">

User ต้องกดปุ่มเพื่อ fetch 5 ข้อมูลล่าสุด

**Comment by vsupacha** [comment]
OK
